### ISSUE TITLE
Basic Commands: Copy, Cut & Paste

### ISSUE THREAD

**Issue by Rodielm** [jmjuanes/folio#1]
It's useful to have this shortcut if you want to duplicate the figure or drawing you've made.

Ctrl + V: Cut
Ctrl + C: Copy
Ctrl + V: Paste

![basicShorcut](https://user-images.githubusercontent.com/10471758/180593733-487cceb0-71c8-4d4e-adda-1c0228a86141.gif)

**Comment by jmjuanes** [comment]
Hi @Rodielm . This has been added in commit c454e08a01be14a2952e008260ecbf07d7eb7db0. Thanks!
