### ISSUE TITLE
New feature: Paste the clipboard by mouse position

### ISSUE THREAD

**Issue by Rodielm** [jmjuanes/folio#17]
### Is your feature request related to a problem?

When copying and pasting a shape or any figure, I need to move it to the position I want.

![clipboard2](https://user-images.githubusercontent.com/10471758/230793002-f21c85ce-bdc9-455c-b043-d2ef3aca5d76.gif)

### Describe the solution you'd like

Is it possible to paste the clipboard by mouse position?

Expected:
![clipboard1](https://user-images.githubusercontent.com/10471758/230792983-bad5a31d-7240-4e06-a4d7-77ebf43f1799.gif)

**Comment by jmjuanes** [comment]
Hi @Rodielm. We have fixed this issue with the context menu, so now you can copy and paste elements in the current position of the mouse:

![Peek 2023-05-05 00-45](https://user-images.githubusercontent.com/5751201/236345521-65862329-f9e1-4762-b42f-478b2c9af93b.gif)
