### ISSUE TITLE
Typing doesn't work

### ISSUE THREAD

**Issue by Rodielm** [jmjuanes/folio#2]
## **Actual Behaviour**

It doesn't allow me to type anything
![textNotWorking](https://user-images.githubusercontent.com/10471758/180594070-cccb4350-fd41-4fc5-945d-af102ee6e695.gif)

## **Expected Behaviour**

- Allow writing in box
- Allow writing on the canvas

**Comment by jmjuanes** [comment]
Hi @Rodielm. Fixed in commit 3ce0505d2568328493ca085fdc90fa4c34538966. Thanks!
